name: FreedomOpMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.0
description: Plugin for the Total Freedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
depend: [BarAPI]
authors: [Madgeek1450, DarthSalamon, Camzie99]

# plugin.yml is no longer used to define commands.
